"""Export local first-order sensitivity tables from the saved step-size study.

Input provenance: `C_results/step_size_table.csv`, generated by
`F_analysis/solve_step_size.py`.

Outputs:
- `C_results/sensitivity_analysis.xlsx`
- `C_results/sensitivity_table.csv`
- `C_results/sensitivity_thesis_table.csv`
"""

from __future__ import annotations

from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    # Allows direct execution as `python F_analysis/sensitivity.py`.
    sys.path.insert(0, str(PROJECT_ROOT))

import F_analysis.sensitivity_core as sensitivity_core

# =============================================================================
# SECTION MAP
# =============================================================================
# 1) CLI entry point
# =============================================================================

# =============================================================================
# 1) CLI Entry Point
# =============================================================================


def main() -> None:
    # Uses the saved ladder so sensitivity export does not rerun optimization.
    sensitivity_core.export_saved_step_size_analysis()


if __name__ == "__main__":
    main()
