from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd


DEFAULT_R5_ROOT = Path("03_Control/05_Results/R5_dense/E01")
DEFAULT_R7_ROOT = Path("03_Control/05_Results/R7_survival/E01")
DEFAULT_R8_LIBRARY_ROOT = Path("03_Control/05_Results/R8_library_size_study/E01")
DEFAULT_R8_OUTCOME_ROOT = Path("03_Control/05_Results/R8_outcome/E01")
DEFAULT_R10_ROOT = Path("03_Control/05_Results/R10_learn/E01")
DEFAULT_R11_ROOT = Path("03_Control/05_Results/R11_validation/E01")
DEFAULT_OUTPUT = Path("03_Control/A_figures/E01_appendix_evidence_tables/e01_evidence_chain_appendix_tables.tex")

SPEED_ORDER = (
    "v0_lt_4_0_m_s",
    "v0_4_0_to_5_0_m_s",
    "v0_5_0_to_6_0_m_s",
    "v0_6_0_to_7_0_m_s",
    "v0_ge_7_0_m_s",
)
SPEED_LABELS = {
    "v0_lt_4_0_m_s": r"$<4.0$",
    "v0_4_0_to_5_0_m_s": r"$4.0$--$5.0$",
    "v0_5_0_to_6_0_m_s": r"$5.0$--$6.0$",
    "v0_6_0_to_7_0_m_s": r"$6.0$--$7.0$",
    "v0_ge_7_0_m_s": r"$\geq 7.0$",
}

LIBRARY_ORDER = (
    "heavy_cluster",
    "balanced_cluster",
    "light_cluster",
    "super_light_cluster",
    "no_cluster_no_merge",
)
LIBRARY_LABELS = {
    "heavy_cluster": "Heavy",
    "balanced_cluster": "Balanced",
    "light_cluster": "Light",
    "super_light_cluster": "Super-light",
    "no_cluster_no_merge": "No-cluster",
}

POLICY_ORDER = (
    "no_memory_baseline",
    "spatial_flow_belief_memory_h3",
    "spatial_flow_belief_memory_h10",
    "spatial_flow_belief_memory_h30",
)
POLICY_LABELS = {
    "no_memory_baseline": r"$h=0$",
    "spatial_flow_belief_memory_h3": r"$h=3$",
    "spatial_flow_belief_memory_h10": r"$h=10$",
    "spatial_flow_belief_memory_h30": r"$h=30$",
}

PRIMITIVE_LABELS = {
    "energy_retaining_bank": "Energy-retaining bank",
    "glide": "Glide",
    "lift_dwell_arc": "Lift-dwell arc",
    "lift_entry": "Lift entry",
    "mild_turn_left": "Mild turn left",
    "mild_turn_right": "Mild turn right",
    "recovery": "Recovery",
    "safe_exit_or_recovery_handoff": "Safe-exit/recovery handoff",
}


@dataclass(frozen=True)
class ColumnSpec:
    key: str
    header: str
    fmt: str = "text"
    higher_is_better: bool | None = None
    raw_latex: bool = False
    count_key: str | None = None
    denom_key: str | None = None


@dataclass(frozen=True)
class SpeedMetric:
    source: str
    header: str
    fmt: str
    higher_is_better: bool
    count_source: str | None = None


SPEED_METRICS = (
    SpeedMetric("mission_success_rate", r"Target", "pct", True, "mission_success_count"),
    SpeedMetric("safe_success_rate", r"Safe", "pct", True, "safe_success_count"),
    SpeedMetric("front_wall_terminal_success_rate", r"Front", "pct", True, "front_wall_terminal_success_count"),
    SpeedMetric("wrong_wall_exit_rate", r"Side", "pct", False, "wrong_wall_exit_count"),
    SpeedMetric("expected_low_energy_dry_air_sink_rate", r"Sink", "pct", False, "expected_low_energy_dry_air_sink_count"),
    SpeedMetric("no_viable_primitive_rate", r"NoPr", "pct", False, "no_viable_primitive_count"),
    SpeedMetric("hard_failure_rate", r"Hard", "pct", False, "hard_failure_count"),
    SpeedMetric("mean_launch_score", r"$\bar{J}$", "score", True),
    SpeedMetric("median_launch_score", r"$\tilde{J}$", "score", True),
    SpeedMetric("mean_terminal_specific_energy_m", r"$E_T$", "energy", True),
    SpeedMetric("mean_terminal_specific_energy_reserve_m", r"$E_R$", "energy", True),
    SpeedMetric("mean_positive_specific_energy_gain_m", r"$E_+$", "energy", True),
    SpeedMetric("mean_updraft_specific_energy_gain_proxy_m", r"$E_u$", "energy", True),
    SpeedMetric("mean_lift_dwell_time_s", r"$t_L$", "time", True),
)

SPEED_TABLE_WEIGHTS = (
    1.30,
    1.45,
    0.50,
    0.45,
    0.85,
    0.80,
    0.80,
    0.75,
    0.80,
    0.75,
    0.75,
    1.05,
    1.05,
    1.00,
    1.00,
    1.00,
    1.00,
    0.90,
)


def main() -> None:
    args = _parse_args()
    tex = build_appendix_tables(args)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(tex, encoding="ascii")
    print(args.output)


def build_appendix_tables(args: argparse.Namespace) -> str:
    lines = [
        r"% Auto-generated by 03_Control/01_Plotting/run_appendix_evidence_tables.py.",
        r"% Complementary appendix tables for R5/R7/R8/R10. R11 speed tables are generated by run_r11_appendix_speed_tables.py.",
        r"% Each table uses width=16.2cm. Column X weights are chosen to sum to 16.2.",
        "",
    ]
    lines.extend(_r5_tables(args.r5_root))
    lines.append("")
    lines.extend(_r7_tables(args.r7_root))
    lines.append("")
    lines.extend(_r8_tables(args.r8_library_root, args.r8_outcome_root))
    lines.append("")
    lines.extend(_r10_tables(args.r10_root))
    lines.append("")
    lines.extend(_reproducibility_tables(args))
    return "\n".join(lines).rstrip() + "\n"


def _r5_tables(r5_root: Path) -> list[str]:
    train = _read_csv(r5_root / "metrics" / "r5_transition_candidate_training_summary.csv")
    selected = _read_csv(r5_root / "metrics" / "r5_transition_selected_for_r7.csv")

    grouped = (
        train.groupby("primitive_id", dropna=False)
        .agg(
            candidate_configurations=("primitive_variant_id", "count"),
            rollout_rows=("row_count", "sum"),
            transition_success_count=("transition_success_count", "sum"),
            hard_failure_count=("hard_failure_count", "sum"),
            worst_environment_success_rate=("worst_environment_success_rate", "mean"),
            updraft_gain_proxy_mean_m=("updraft_gain_proxy_mean_m", "mean"),
            lift_dwell_mean_s=("lift_dwell_mean_s", "mean"),
            saturation_mean=("saturation_mean", "mean"),
            r5_transition_training_score=("r5_transition_training_score", "mean"),
        )
        .reset_index()
    )
    selected_grouped = (
        selected.groupby("primitive_id", dropna=False)
        .agg(
            selected_transition_objects=("primitive_variant_id", "count"),
            selected_unique_variants=("primitive_variant_id", "nunique"),
            selected_speed_bin_count=("local_lqr_speed_bin_id", "nunique"),
        )
        .reset_index()
    )
    family = grouped.merge(selected_grouped, on="primitive_id", how="left")
    family["primitive_label"] = family["primitive_id"].map(PRIMITIVE_LABELS).fillna(family["primitive_id"])
    family["transition_success_rate"] = _safe_div(family["transition_success_count"], family["rollout_rows"])
    family["hard_failure_rate"] = _safe_div(family["hard_failure_count"], family["rollout_rows"])
    family = family.sort_values("primitive_label")

    entry = (
        selected.groupby("transition_entry_class", dropna=False)
        .agg(
            selected_transition_objects=("primitive_variant_id", "count"),
            primitive_family_count=("primitive_id", "nunique"),
            selected_unique_variants=("primitive_variant_id", "nunique"),
            selected_speed_bin_count=("local_lqr_speed_bin_id", "nunique"),
            min_reference_speed_m_s=("local_lqr_reference_speed_m_s", "min"),
            max_reference_speed_m_s=("local_lqr_reference_speed_m_s", "max"),
            transition_success_count=("transition_success_count", "sum"),
            rollout_rows=("row_count", "sum"),
            hard_failure_count=("hard_failure_count", "sum"),
            r5_transition_training_score=("r5_transition_training_score", "mean"),
        )
        .reset_index()
    )
    entry["transition_success_rate"] = _safe_div(entry["transition_success_count"], entry["rollout_rows"])
    entry["hard_failure_rate"] = _safe_div(entry["hard_failure_count"], entry["rollout_rows"])
    entry["entry_label"] = entry["transition_entry_class"].map(_human_label).fillna(entry["transition_entry_class"].map(str))
    entry = entry.sort_values("transition_entry_class")

    lines = [
        r"\subsection{Dense Primitive Synthesis Tables}",
        "",
        r"\noindent\footnotesize",
        r"These tables summarise the dense primitive-synthesis stage used before any repeated-launch memory is introduced.",
        r"The controller designs are fixed transition-aware LQR primitives executed through the real-flight-aligned actuator, command-lattice, and latency model.",
        r"Where a success or failure rate has a direct numerator and denominator, the cell reports count/$n$ (percentage) rather than a percentage alone.",
        r"R5 is therefore evidence about whether the primitive library contains physically executable manoeuvres and whether each primitive family contributes useful candidates for later survival screening.",
        "",
    ]
    lines.extend(
        _generic_table(
            family,
            caption=(
                "R5 dense primitive synthesis by primitive family. "
                "Rows report how many candidate configurations were tested, how many rollout samples they produced, and how much evidence was retained for the survival-screening stage."
            ),
            label="tab:appendix-r5-family-synthesis",
            columns=(
                ColumnSpec("primitive_label", "Primitive family"),
                ColumnSpec("candidate_configurations", "Configs", "int"),
                ColumnSpec("rollout_rows", "Rollouts", "int"),
                ColumnSpec("selected_transition_objects", "R7 rows", "int", True),
                ColumnSpec("selected_unique_variants", "Variants", "int", True),
                ColumnSpec("selected_speed_bin_count", "Speeds", "int", True),
                ColumnSpec("transition_success_rate", "Success", "pct", True, count_key="transition_success_count", denom_key="rollout_rows"),
                ColumnSpec("worst_environment_success_rate", "Worst env.", "pct", True),
                ColumnSpec("hard_failure_rate", "Hard", "pct", False, count_key="hard_failure_count", denom_key="rollout_rows"),
                ColumnSpec("updraft_gain_proxy_mean_m", r"$E_u$", "energy", True),
                ColumnSpec("lift_dwell_mean_s", r"$t_L$", "time", True),
                ColumnSpec("saturation_mean", "Sat.", "pct", False),
                ColumnSpec("r5_transition_training_score", "Score", "float3", True),
            ),
            weights=(4.20, 0.90, 1.00, 1.00, 0.95, 0.85, 1.10, 1.25, 0.90, 1.00, 0.90, 0.95, 1.20),
        )
    )
    lines.append("")
    lines.extend(
        _generic_table(
            entry,
            caption=(
                "R5 selected transition-object coverage by entry class. "
                "This table shows whether the selected primitive set spans launch-gate, in-flight, boundary-near, and recovery handoff conditions before R7 replay."
            ),
            label="tab:appendix-r5-entry-coverage",
            columns=(
                ColumnSpec("entry_label", "Transition entry class"),
                ColumnSpec("selected_transition_objects", "R7 rows", "int", True),
                ColumnSpec("selected_unique_variants", "Variants", "int", True),
                ColumnSpec("primitive_family_count", "Families", "int", True),
                ColumnSpec("selected_speed_bin_count", "Speeds", "int", True),
                ColumnSpec("min_reference_speed_m_s", r"$v_{\min}$", "float1", False),
                ColumnSpec("max_reference_speed_m_s", r"$v_{\max}$", "float1", True),
                ColumnSpec("transition_success_rate", "Success", "pct", True, count_key="transition_success_count", denom_key="rollout_rows"),
                ColumnSpec("hard_failure_rate", "Hard", "pct", False, count_key="hard_failure_count", denom_key="rollout_rows"),
                ColumnSpec("r5_transition_training_score", "Score", "float3", True),
            ),
            weights=(4.00, 1.35, 1.35, 1.15, 1.10, 1.05, 1.05, 1.60, 1.40, 2.15),
        )
    )
    return lines


def _r7_tables(r7_root: Path) -> list[str]:
    survival = _read_csv(r7_root / "metrics" / "w3_variant_survival_summary.csv")
    failure = _read_csv(r7_root / "metrics" / "w3_failure_summary.csv")

    grouped = (
        survival.groupby("primitive_id", dropna=False)
        .agg(
            replayed_transition_objects=("primitive_variant_id", "count"),
            eligible_for_r8=("eligible_for_post_w3_library_size_study", _sum_bool),
            compatible_rows=("compatible_row_count", "sum"),
            incompatible_rows=("incompatible_row_count", "sum"),
            continuation_valid_count=("continuation_valid_count", "sum"),
            episode_terminal_useful_count=("episode_terminal_useful_count", "sum"),
            transition_chain_compatible_count=("transition_chain_compatible_count", "sum"),
            hard_failure_count=("hard_failure_count", "sum"),
            floor_margin_min_m=("floor_margin_min_m", "min"),
            ceiling_margin_min_m=("ceiling_margin_min_m", "min"),
            energy_residual_mean_m=("energy_residual_mean_m", "mean"),
            lift_dwell_mean_s=("lift_dwell_mean_s", "mean"),
        )
        .reset_index()
    )
    grouped["replay_rows"] = grouped["compatible_rows"] + grouped["incompatible_rows"]
    grouped["transition_chain_compatible_rate"] = _safe_div(grouped["transition_chain_compatible_count"], grouped["replay_rows"])
    grouped["continuation_valid_rate"] = _safe_div(grouped["continuation_valid_count"], grouped["replay_rows"])
    grouped["terminal_useful_rate"] = _safe_div(grouped["episode_terminal_useful_count"], grouped["replay_rows"])
    grouped["hard_failure_rate"] = _safe_div(grouped["hard_failure_count"], grouped["replay_rows"])
    grouped["primitive_label"] = grouped["primitive_id"].map(PRIMITIVE_LABELS).fillna(grouped["primitive_id"])
    grouped = grouped.sort_values("primitive_label")

    total = float(failure["row_count"].sum()) if not failure.empty else 0.0
    failure_rows = failure.copy()
    failure_rows["rate"] = _safe_div(failure_rows["row_count"], total)
    failure_rows["label"] = failure_rows["value"].map(_human_label)
    failure_rows["interpretation"] = failure_rows["value"].map(_r7_failure_interpretation).fillna("Physical replay outcome retained for audit.")
    failure_rows = failure_rows.sort_values(["summary_axis", "value"])

    lines = [
        r"\subsection{Survival Screening Tables}",
        "",
        r"\noindent\footnotesize",
        r"These tables report the fixed-controller survival replay used after dense synthesis.",
        r"The B-series evidence uses the current R7 survival stage; earlier R6 archived folders are historical diagnostics and are not the claim-bearing source for R8.",
        r"No LQR controller is retuned here: R7 only replays the frozen R5 candidates under broader environment and implementation variation, then passes eligible transition objects to compression.",
        r"Count-backed survival rates are reported as count/$n$ (percentage) so the reader can see both the evidence size and the estimated rate.",
        "",
    ]
    lines.extend(
        _generic_table(
            grouped,
            caption=(
                "R7 fixed-controller survival replay by primitive family. "
                "Rows show how many transition objects remain eligible for library compression and whether survival failures remain physically explainable."
            ),
            label="tab:appendix-r7-survival-family",
            columns=(
                ColumnSpec("primitive_label", "Primitive family"),
                ColumnSpec("replayed_transition_objects", "Replayed", "int"),
                ColumnSpec("eligible_for_r8", "R8 elig.", "int", True),
                ColumnSpec("compatible_rows", "Compat.", "int", True),
                ColumnSpec("transition_chain_compatible_rate", "Chain", "pct", True, count_key="transition_chain_compatible_count", denom_key="replay_rows"),
                ColumnSpec("continuation_valid_rate", "Cont.", "pct", True, count_key="continuation_valid_count", denom_key="replay_rows"),
                ColumnSpec("terminal_useful_rate", "Term.", "pct", True, count_key="episode_terminal_useful_count", denom_key="replay_rows"),
                ColumnSpec("hard_failure_rate", "Hard", "pct", False, count_key="hard_failure_count", denom_key="replay_rows"),
                ColumnSpec("floor_margin_min_m", "Floor", "energy", True),
                ColumnSpec("ceiling_margin_min_m", "Ceil.", "energy", True),
                ColumnSpec("energy_residual_mean_m", r"$\Delta E$", "energy", True),
                ColumnSpec("lift_dwell_mean_s", r"$t_L$", "time", True),
            ),
            weights=(3.85, 1.05, 1.05, 1.15, 1.10, 1.10, 1.10, 0.95, 1.05, 1.05, 1.25, 1.50),
        )
    )
    lines.append("")
    lines.extend(
        _generic_table(
            failure_rows,
            caption=(
                "R7 survival-screening outcome and failure interpretation. "
                "The table separates successful replay from boundary and model-envelope outcomes so that later library coverage limits can be interpreted physically."
            ),
            label="tab:appendix-r7-failure-interpretation",
            columns=(
                ColumnSpec("summary_axis", "Audit axis"),
                ColumnSpec("label", "Outcome label"),
                ColumnSpec("row_count", "Rows", "int"),
                ColumnSpec("rate", "Rate", "pct"),
                ColumnSpec("interpretation", "Interpretation"),
            ),
            weights=(2.00, 3.10, 1.20, 1.20, 8.70),
            rows_font=r"\scriptsize",
        )
    )
    return lines


def _r8_tables(r8_root: Path, outcome_root: Path) -> list[str]:
    library = _read_csv(r8_root / "metrics" / "library_size_case_summary.csv")
    speed = _read_csv(r8_root / "metrics" / "speed_bin_coverage_audit.csv")
    medoid = _read_csv(r8_root / "metrics" / "coverage_medoid_selection_audit.csv")
    outcome = _read_csv(outcome_root / "metrics" / "outcome_model_summary.csv")

    baseline_count = float(
        library.loc[library["library_size_case_id"] == "no_cluster_no_merge", "representative_count"].iloc[0]
    )
    speed_summary = (
        speed.groupby("library_size_case_id", dropna=False)
        .agg(
            speed_audit_rows=("speed_bin_coverage_status", "count"),
            speed_coverage_passed=("speed_bin_coverage_status", lambda s: int((s.astype(str) == "passed").sum())),
            selected_speed_bin_count=("selected_speed_bin_count", "mean"),
            source_speed_bin_count=("source_speed_bin_count", "mean"),
        )
        .reset_index()
    )
    speed_summary["speed_coverage_pass_rate"] = _safe_div(
        speed_summary["speed_coverage_passed"], speed_summary["speed_audit_rows"]
    )
    outcome_summary = (
        outcome.groupby("library_size_case_id", dropna=False)
        .agg(
            outcome_rows=("compact_library_id", "count"),
            primitive_family_count=("primitive_id", "nunique"),
            transition_entry_class_count=("transition_entry_class", "nunique"),
            transition_success_probability=("transition_success_probability", "mean"),
            continuation_probability=("continuation_probability", "mean"),
            hard_failure_risk=("hard_failure_risk", "mean"),
            expected_energy_residual_m=("expected_energy_residual_m", "mean"),
            expected_lift_dwell_time_s=("expected_lift_dwell_time_s", "mean"),
        )
        .reset_index()
    )
    case_summary = library.merge(speed_summary, on="library_size_case_id", how="left").merge(
        outcome_summary, on="library_size_case_id", how="left"
    )
    case_summary["library_label"] = case_summary["library_size_case_id"].map(LIBRARY_LABELS)
    case_summary["compression_ratio"] = baseline_count / case_summary["representative_count"]
    case_summary = _order_by_case(case_summary)

    entry_summary = (
        medoid.groupby(["library_size_case_id", "transition_entry_class"], dropna=False)
        .agg(
            representative_count=("transition_object_id", "count"),
            primitive_family_count=("primitive_id", "nunique"),
            speed_bin_count=("local_lqr_speed_bin_id", "nunique"),
            mean_reference_speed_m_s=("local_lqr_reference_speed_m_s", "mean"),
            mean_coverage_gain=("coverage_marginal_gain", "mean"),
            mean_medoid_quality=("medoid_quality_score", "mean"),
            mean_distance_to_center=("medoid_distance_to_group_center", "mean"),
        )
        .reset_index()
    )
    entry_summary["library_label"] = entry_summary["library_size_case_id"].map(LIBRARY_LABELS)
    entry_summary["entry_label"] = entry_summary["transition_entry_class"].map(_human_label)
    entry_summary = _order_by_case(entry_summary).sort_values(["case_order", "transition_entry_class"])

    lines = [
        r"\subsection{Library Compression and Outcome-Model Tables}",
        "",
        r"\noindent\footnotesize",
        r"These tables report how the R7 survival set is compressed into online primitive-library tiers.",
        r"Compression is coverage-aware: the medoid selection keeps primitive-family, transition-entry-class, and local speed-bin evidence instead of selecting only the highest nominal score.",
        r"Count-backed coverage rates are reported as count/$n$ (percentage); model probabilities without a direct per-table denominator remain reported as percentages.",
        r"The outcome model remains simulation-only evidence used by the outer-loop governor; it does not mutate the frozen primitive controllers.",
        "",
    ]
    lines.extend(
        _generic_table(
            case_summary,
            caption=(
                "R8 library-size tiers and outcome-model summary. "
                "The no-cluster tier is the offline reference, while heavy and balanced are the primary real-flight candidate tiers."
            ),
            label="tab:appendix-r8-library-tier-summary",
            columns=(
                ColumnSpec("library_label", "Library tier"),
                ColumnSpec("representative_count", "Reps.", "int", False),
                ColumnSpec("compression_ratio", "Comp.", "float1", True),
                ColumnSpec("primitive_family_count", "Families", "int", True),
                ColumnSpec("transition_entry_class_count", "Entries", "int", True),
                ColumnSpec("speed_coverage_pass_rate", "Speed cov.", "pct", True, count_key="speed_coverage_passed", denom_key="speed_audit_rows"),
                ColumnSpec("selected_speed_bin_count", "Sel. speeds", "float1", True),
                ColumnSpec("transition_success_probability", "Success", "pct", True),
                ColumnSpec("continuation_probability", "Cont.", "pct", True),
                ColumnSpec("hard_failure_risk", "Hard risk", "pct", False),
                ColumnSpec("expected_energy_residual_m", r"$\Delta E$", "energy", True),
                ColumnSpec("expected_lift_dwell_time_s", r"$t_L$", "time", True),
            ),
            weights=(4.30, 1.00, 1.00, 1.00, 1.00, 1.25, 1.25, 1.15, 1.10, 1.15, 1.00, 1.00),
        )
    )
    lines.append("")
    lines.extend(
        _generic_table(
            entry_summary,
            caption=(
                "R8 coverage-aware medoid selection by transition-entry class. "
                "The table shows how each compression tier preserves entry-condition and speed-bin coverage for the receding-horizon selector."
            ),
            label="tab:appendix-r8-entry-medoid-coverage",
            columns=(
                ColumnSpec("library_label", "Library tier"),
                ColumnSpec("entry_label", "Entry class"),
                ColumnSpec("representative_count", "Reps.", "int", True),
                ColumnSpec("primitive_family_count", "Families", "int", True),
                ColumnSpec("speed_bin_count", "Speeds", "int", True),
                ColumnSpec("mean_reference_speed_m_s", r"$\bar{v}$", "float1", True),
                ColumnSpec("mean_coverage_gain", "Cov. gain", "float3", True),
                ColumnSpec("mean_medoid_quality", "Quality", "float3", True),
                ColumnSpec("mean_distance_to_center", "Dist.", "float2", False),
            ),
            weights=(2.10, 2.40, 1.10, 1.10, 1.10, 1.10, 1.95, 2.00, 3.35),
            rows_font=r"\tiny",
        )
    )
    return lines


def _r10_tables(r10_root: Path) -> list[str]:
    speed = _read_csv(r10_root / "metrics" / "speed_bin_policy_ladder_summary.csv")
    policy = _read_csv(r10_root / "metrics" / "policy_history_comparison.csv")
    paired = _read_csv(r10_root / "metrics" / "paired_score_delta_summary.csv")
    memory = _read_csv(r10_root / "metrics" / "memory_opportunity_summary.csv")
    timing = _read_csv(r10_root / "metrics" / "real_time_scheduler_audit.csv")
    termination = _read_csv(r10_root / "metrics" / "termination_summary.csv")
    interpretation = _read_csv(r10_root / "metrics" / "episode_interpretation_summary.csv")

    lines = [
        r"\subsection{Governor Learning and Calibration Tables}",
        "",
        r"\noindent\footnotesize",
        r"These tables report the R10 full-domain governor-learning run.",
        r"R10 uses the frozen R8 library and learns only through the outer-loop governor: case-local repeated-launch flow belief is updated online, then aggregate R10 evidence freezes one bounded governor configuration for R11.",
        r"Where a rate has a clear numerator and denominator, the cell reports count/$n$ (percentage) so that unequal speed-bin sample sizes remain visible.",
        r"No primitive controller is retrained and no fan-layout-specific branch is introduced.",
        "",
    ]
    lines.extend(_speed_cluster_policy_table(speed, stage="r10", caption=(
        "R10 full-domain governor-learning result conditioned on launch speed, primitive-library tier, and repeated-launch history length. "
        "This is the direct calibration-stage companion to the R11 held-out appendix table."
    ), label="tab:appendix-r10-speed-cluster-policy"))
    lines.append("")

    paired_small = paired[paired["comparison_type"].astype(str) == "memory_vs_no_memory"].copy()
    memory_policy = policy.merge(
        paired_small[
            [
                "library_size_case_id",
                "policy_id",
                "paired_launch_count",
                "mean_paired_delta_launch_score",
                "win_rate",
                "loss_rate",
                "safety_regression_rate",
            ]
        ],
        on=["library_size_case_id", "policy_id"],
        how="left",
    )
    memory_policy["library_label"] = memory_policy["library_size_case_id"].map(LIBRARY_LABELS)
    memory_policy["policy_label"] = memory_policy["policy_id"].map(POLICY_LABELS)
    memory_policy["mission_success_count"] = memory_policy["mission_success_rate"] * memory_policy["launch_count"]
    memory_policy["safe_success_count"] = memory_policy["safe_success_rate"] * memory_policy["launch_count"]
    memory_policy["win_count"] = memory_policy["win_rate"] * memory_policy["paired_launch_count"]
    memory_policy["loss_count"] = memory_policy["loss_rate"] * memory_policy["paired_launch_count"]
    memory_policy["safety_regression_count"] = memory_policy["safety_regression_rate"] * memory_policy["paired_launch_count"]
    memory_policy["memory_changed_selection_count"] = (
        memory_policy["memory_changed_selection_rate"] * memory_policy["launch_count"]
    )
    memory_policy = _order_by_case(memory_policy)
    memory_policy["policy_order"] = memory_policy["policy_id"].map({key: i for i, key in enumerate(POLICY_ORDER)})
    memory_policy = memory_policy.sort_values(["case_order", "policy_order"])

    lines.extend(
        _generic_table(
            memory_policy,
            caption=(
                "R10 memory activity and paired effect by library tier. "
                "Rows compare the no-memory baseline against h3, h10, and h30 repeated-launch memory while preserving paired launch starts."
            ),
            label="tab:appendix-r10-memory-policy-effect",
            columns=(
                ColumnSpec("library_label", "Library tier"),
                ColumnSpec("policy_label", "$h$", raw_latex=True),
                ColumnSpec("launch_count", "$n$", "int"),
                ColumnSpec("mission_success_rate", "Target", "pct", True, count_key="mission_success_count", denom_key="launch_count"),
                ColumnSpec("safe_success_rate", "Safe", "pct", True, count_key="safe_success_count", denom_key="launch_count"),
                ColumnSpec("mean_launch_score", r"$\bar{J}$", "score", True),
                ColumnSpec("mean_paired_delta_launch_score", r"$\Delta J$", "score", True),
                ColumnSpec("win_rate", "Win", "pct", True, count_key="win_count", denom_key="paired_launch_count"),
                ColumnSpec("loss_rate", "Loss", "pct", False, count_key="loss_count", denom_key="paired_launch_count"),
                ColumnSpec("safety_regression_rate", "Regress", "pct", False, count_key="safety_regression_count", denom_key="paired_launch_count"),
                ColumnSpec("memory_changed_selection_rate", "Mem. sel.", "pct", True, count_key="memory_changed_selection_count", denom_key="launch_count"),
                ColumnSpec("belief_observation_count", "Obs.", "int", True),
                ColumnSpec("belief_uncertainty", "Uncert.", "float3", False),
            ),
            weights=(3.10, 0.65, 0.65, 1.05, 1.00, 1.10, 1.10, 0.90, 0.90, 1.05, 1.15, 1.05, 2.50),
            rows_font=r"\tiny",
        )
    )
    lines.append("")

    overall_memory = memory[memory["audit_scope"].astype(str) == "overall"].copy()
    if not overall_memory.empty:
        overall_memory["audit_label"] = "Overall memory selector audit"
        lines.extend(
            _generic_table(
                overall_memory,
                caption=(
                    "R10 aggregate memory-opportunity audit. "
                    "The table reports how often the memory-assisted selector had a chance to change the no-memory choice and how often that switch was accepted."
                ),
                label="tab:appendix-r10-memory-opportunity",
                columns=(
                    ColumnSpec("audit_label", "Audit scope"),
                    ColumnSpec("decision_count", "Decisions", "int"),
                    ColumnSpec("memory_policy_decision_count", "Mem. dec.", "int", True),
                    ColumnSpec("memory_switch_available_count", "Opport.", "int", True),
                    ColumnSpec("accepted_memory_switch_count", "Accepted", "int", True),
                    ColumnSpec("rejected_memory_switch_count", "Rejected", "int", False),
                    ColumnSpec("mean_memory_cost_benefit_net_value", "Net", "float3", True),
                    ColumnSpec("mean_adaptive_score_margin", "Margin", "float3", True),
                    ColumnSpec("memory_policy_version", "Policy version"),
                ),
                weights=(2.60, 1.10, 1.10, 1.05, 1.05, 1.05, 1.05, 1.05, 6.15),
                rows_font=r"\scriptsize",
            )
        )
        lines.append("")

    timing_table = timing.copy()
    timing_table["audit_label"] = timing_table["audit_scope"].map(_timing_scope_label).fillna(timing_table["audit_scope"])
    lines.extend(
        _generic_table(
            timing_table,
            caption=(
                "R10 selector timing audit. "
                "Heavy and balanced tiers are the real-flight claim-bearing online tiers; larger tiers are retained as diagnostics or offline comparisons."
            ),
            label="tab:appendix-r10-timing-audit",
            columns=(
                ColumnSpec("audit_label", "Timing scope"),
                ColumnSpec("selector_decision_count", "Decisions", "int"),
                ColumnSpec("preferred_20ms_slot_met_rate", "20 ms", "pct", True, count_key="preferred_20ms_slot_met_count", denom_key="selector_decision_count"),
                ColumnSpec("hard_100ms_boundary_met_rate", "100 ms", "pct", True, count_key="hard_100ms_boundary_met_count", denom_key="selector_decision_count"),
                ColumnSpec("mean_decision_total_duration_s", "Mean", "time", False),
                ColumnSpec("p99_decision_total_duration_s", "p99", "time", False),
                ColumnSpec("max_decision_total_duration_s", "Max", "time", False),
                ColumnSpec("mean_evaluated_candidate_count", "Eval.", "float1", False),
                ColumnSpec("max_evaluated_candidate_count", "Max cand.", "int", False),
                ColumnSpec("real_time_claim_status", "Claim status"),
            ),
            weights=(2.65, 1.00, 1.00, 1.05, 0.90, 0.90, 0.90, 1.00, 1.05, 5.75),
            rows_font=r"\scriptsize",
        )
    )
    lines.append("")
    lines.extend(_r10_failure_table(termination, interpretation))
    return lines


def _reproducibility_tables(args: argparse.Namespace) -> list[str]:
    r5_manifest = _read_json(args.r5_root / "manifests" / "run_manifest.json")
    r7_manifest = _read_json(args.r7_root / "manifests" / "w3_survival_manifest.json")
    r8_manifest = _read_json(args.r8_library_root / "manifests" / "post_w3_library_size_study_manifest.json")
    r10_manifest = _read_json(args.r10_root / "manifests" / "environment_changed_case_manifest.json")
    r10_governor = _read_json(args.r10_root / "manifests" / "frozen_governor_config_for_r11.json")
    r11_roots = [args.r11_root] + list(args.extra_r11_root or [])
    r11_manifests = [_read_json(root / "manifests" / "heldout_environment_validation_manifest.json") for root in r11_roots]
    timing = _read_csv(args.r5_root / "metrics" / "timing_contract_audit.csv")
    timing_row = timing.iloc[0].to_dict() if not timing.empty else {}
    primitive_contract = r5_manifest.get("primitive_timing_contract", {})
    history_values = [0] + [int(h) for h in r10_manifest.get("history_lengths", [3, 10, 30])]
    r8_tiers = ", ".join(LIBRARY_LABELS.get(str(x), str(x)) for x in r8_manifest.get("library_size_case_ids", []))
    r11_expected_final = sum(
        int(_finite_float(manifest.get("expected_final_heldout_launches")) or 0) for manifest in r11_manifests
    )
    paired_cases_per_ladder = int(round(r11_expected_final / (8 * 5 * 4))) if r11_expected_final else "--"
    r11_outer_total = int(round(r11_expected_final / (5 * 4))) if r11_expected_final else "--"
    r11_run_labels = "+".join(str(manifest.get("run_label", root.name)) for manifest, root in zip(r11_manifests, r11_roots))
    r11_actual_final = sum(int(_finite_float(manifest.get("actual_final_heldout_launches")) or 0) for manifest in r11_manifests)
    r11_actual_history = sum(int(_finite_float(manifest.get("actual_history_launches")) or 0) for manifest in r11_manifests)

    rows = pd.DataFrame(
        [
            {
                "setting": "R5 dense primitive synthesis",
                "value": f"{r5_manifest.get('run_label', 'E01')}; {r5_manifest.get('actual_row_count', '--')} rollout rows; seed {r5_manifest.get('seed', '--')}",
                "purpose": "Build the frozen transition-aware LQR primitive candidates under the executable actuator and latency model.",
            },
            {
                "setting": "R7 survival replay",
                "value": f"{r7_manifest.get('run_label', 'E01')}; {r7_manifest.get('survivor_count', '--')} eligible transition objects",
                "purpose": "Replay the frozen R5 controllers under broader environment and implementation variation without retuning.",
            },
            {
                "setting": "R8 library tiers",
                "value": r8_tiers,
                "purpose": "Compress the survival set into online library tiers while preserving coverage over primitive family, entry class, and speed bin.",
            },
            {
                "setting": "R10 governor learning",
                "value": f"{r10_manifest.get('run_label', 'E01')}; {r10_manifest.get('actual_final_heldout_launches', '--')} final launches; {r10_manifest.get('actual_history_launches', '--')} history launches",
                "purpose": "Use paired full-domain randomisation to freeze one bounded governor configuration for held-out validation.",
            },
            {
                "setting": "R11 held-out validation",
                "value": f"{r11_run_labels}; {r11_actual_final} final launches; {r11_actual_history} history launches",
                "purpose": "Validate the frozen R10 governor across independent randomized held-out L0--L7 repeats; raw runs stay separate and are aggregated only in post-analysis.",
            },
            {
                "setting": "Repeated-launch histories",
                "value": ", ".join(f"$h={h}$" for h in history_values),
                "purpose": "Compare no memory with online memory updated from the previous launches in the same physical case.",
            },
            {
                "setting": "R11 paired starts",
                "value": f"{paired_cases_per_ladder} paired local cases per ladder across reported repeats ({r11_outer_total} ladder cases total)",
                "purpose": "Reuse launch-state seeds across ladders, library tiers, and memory policies so speed-conditioned comparisons are fair.",
            },
            {
                "setting": "Primitive timing contract",
                "value": f"{primitive_contract.get('finite_horizon_s', 0.1)} s horizon, {primitive_contract.get('controller_input_slots_per_primitive', 5)} command slots, {primitive_contract.get('controller_input_update_period_s', 0.02)} s update",
                "purpose": "Keep every primitive compatible with the 0.1 s receding-horizon governor and 20 ms command update model.",
            },
            {
                "setting": "Command execution",
                "value": r"20\% lattice, $\{-1.0,-0.8,\ldots,0.8,1.0\}$",
                "purpose": "Execute the same quantised aggregate command contract in simulation that the hardware adapter will send to the Arduino path.",
            },
            {
                "setting": "Latency and actuator model",
                "value": (
                    f"state delay {timing_row.get('state_feedback_delay_s_values', '--')} s; "
                    f"command delay {timing_row.get('command_delay_s_values', '--')} s; "
                    f"actuator tau {_compact_tau_string(timing_row.get('actuator_tau_s_values', '--'))}"
                ),
                "purpose": "Represent measured Vicon/command delay and actuator lag without embedding the Arduino/PPM chain in the online governor.",
            },
            {
                "setting": "Governor memory scope",
                "value": "case-local reset per final schedule row",
                "purpose": "Keep repeated-launch flow memory local to one physical case; no cross-case memory or final-run-only logic is used.",
            },
            {
                "setting": "Calibration strategy",
                "value": "deterministic bounded rule update; no black-box search",
                "purpose": "Avoid black-box optimiser behaviour while still allowing R10 aggregate evidence to set one frozen R11 governor.",
            },
        ]
    )

    lines = [
        r"\subsection{Runtime and Reproducibility Tables}",
        "",
        r"\noindent\footnotesize",
        r"This table records the evidence-generation settings needed to interpret the appendix without opening result folders.",
        r"It separates the online controller contract from offline thesis logging: the primitive library and governor see only the canonical state and command interface, while post-processing tables are generated after the run.",
        "",
    ]
    lines.extend(
        _generic_table(
            rows,
            caption=(
                "Reproducibility and real-flight-aligned execution settings for the B/D-series evidence chain. "
                "Rows state what was fixed, what was varied, and why each setting is relevant for interpreting the appendix tables."
            ),
            label="tab:appendix-reproducibility-settings",
            columns=(
                ColumnSpec("setting", "Setting"),
                ColumnSpec("value", "Value", raw_latex=True),
                ColumnSpec("purpose", "Why it matters"),
            ),
            weights=(3.10, 5.00, 8.10),
            rows_font=r"\scriptsize",
        )
    )
    return lines


def _speed_cluster_policy_table(frame: pd.DataFrame, *, stage: str, caption: str, label: str) -> list[str]:
    if frame.empty:
        return []
    ordered = frame.copy()
    ordered["launch_speed_bin_id"] = pd.Categorical(ordered["launch_speed_bin_id"], SPEED_ORDER, ordered=True)
    ordered["library_size_case_id"] = pd.Categorical(ordered["library_size_case_id"], LIBRARY_ORDER, ordered=True)
    ordered["policy_id"] = pd.Categorical(ordered["policy_id"], POLICY_ORDER, ordered=True)
    ordered = ordered.sort_values(["launch_speed_bin_id", "library_size_case_id", "policy_id"])
    extrema = _speed_metric_extrema(ordered)
    lines = [
        r"\begin{longtblr}[",
        rf"  caption = {{{caption}}},",
        rf"  label = {{{label}}},",
        r"]{",
        r"  rows={font=\tiny},",
        r"  width=16.2cm,",
        r"  rowhead=1,",
        r"  rowsep=1pt,",
        r"  colsep=1pt,",
        r"  colspec = {",
        _speed_colspec(),
        r"  },",
        r"}",
        r"\toprule",
        _speed_header_row(),
        r"\midrule",
    ]
    row_counter = 0
    for speed_id in SPEED_ORDER:
        speed_frame = ordered[ordered["launch_speed_bin_id"].astype(str) == speed_id]
        if speed_frame.empty:
            continue
        if row_counter:
            lines.append(r"\midrule")
        speed_started = False
        for library_id in LIBRARY_ORDER:
            library_frame = speed_frame[speed_frame["library_size_case_id"].astype(str) == library_id]
            if library_frame.empty:
                continue
            library_started = False
            for policy_id in POLICY_ORDER:
                row = library_frame[library_frame["policy_id"].astype(str) == policy_id]
                if row.empty:
                    continue
                cells = []
                cells.append(rf"\SetCell[r=20]{{l,m}} {SPEED_LABELS[speed_id]}" if not speed_started else "")
                cells.append(rf"\SetCell[r=4]{{l,m}} {LIBRARY_LABELS[library_id]}" if not library_started else "")
                cells.append(POLICY_LABELS[policy_id])
                cells.append(_format_count(row.iloc[0].get("launch_count", "")))
                for metric in SPEED_METRICS:
                    cells.append(_format_speed_metric(row.iloc[0], metric, extrema))
                lines.append("\n  " + "\n  & ".join(cells) + r" \\")
                speed_started = True
                library_started = True
                row_counter += 1
    lines.extend([r"\bottomrule", r"\end{longtblr}"])
    return lines


def _r10_failure_table(termination: pd.DataFrame, interpretation: pd.DataFrame) -> list[str]:
    rows: list[dict[str, object]] = []
    final_termination = termination[termination["launch_role"].astype(str) == "final_heldout"].copy()
    total_final = float(final_termination["row_count"].sum()) if not final_termination.empty else 0.0
    for _, row in final_termination.iterrows():
        label = _human_label(str(row["termination_cause"]))
        rows.append(
            {
                "category": "Termination",
                "label": label,
                "row_count": row["row_count"],
                "rate": _finite_float(row["row_count"]) / total_final if total_final else math.nan,
                "interpretation": _termination_interpretation(str(row["termination_cause"])),
            }
        )
    final_interpretation = interpretation[interpretation["launch_role"].astype(str) == "final_heldout"].copy()
    total_interpretation = float(final_interpretation["row_count"].sum()) if not final_interpretation.empty else 0.0
    for _, row in final_interpretation.iterrows():
        label = _human_label(str(row["episode_interpretation_label"]))
        rows.append(
            {
                "category": "Episode label",
                "label": label,
                "row_count": row["row_count"],
                "rate": _finite_float(row["row_count"]) / total_interpretation if total_interpretation else math.nan,
                "interpretation": _episode_interpretation(str(row["episode_interpretation_label"])),
            }
        )
    frame = pd.DataFrame(rows)
    if frame.empty:
        return []
    return _generic_table(
        frame,
        caption=(
            "R10 final-launch termination and interpretation audit. "
            "The table distinguishes low-energy or boundary-limited outcomes from claim-bearing hard failures."
        ),
        label="tab:appendix-r10-failure-interpretation",
        columns=(
            ColumnSpec("category", "Category"),
            ColumnSpec("label", "Label"),
            ColumnSpec("row_count", "Rows", "int"),
            ColumnSpec("rate", "Rate", "pct"),
            ColumnSpec("interpretation", "Interpretation"),
        ),
        weights=(2.00, 3.00, 1.20, 1.20, 8.80),
        rows_font=r"\scriptsize",
    )


def _generic_table(
    frame: pd.DataFrame,
    *,
    caption: str,
    label: str,
    columns: tuple[ColumnSpec, ...],
    weights: tuple[float, ...],
    rows_font: str = r"\tiny",
) -> list[str]:
    if len(columns) != len(weights):
        raise ValueError(f"Table {label} has {len(columns)} columns but {len(weights)} weights.")
    if not math.isclose(sum(weights), 16.2, rel_tol=0.0, abs_tol=0.02):
        raise ValueError(f"Table {label} column weights sum to {sum(weights):.3f}, not 16.2.")
    extrema = _column_extrema(frame, columns)
    lines = [
        r"\begin{longtblr}[",
        rf"  caption = {{{caption}}},",
        rf"  label = {{{label}}},",
        r"]{",
        rf"  rows={{font={rows_font}}},",
        r"  width=16.2cm,",
        r"  rowhead=1,",
        r"  rowsep=1pt,",
        r"  colsep=1pt,",
        r"  colspec = {",
        _generic_colspec(columns, weights),
        r"  },",
        r"}",
        r"\toprule",
        _generic_header_row(columns),
        r"\midrule",
    ]
    for _, row in frame.iterrows():
        cells = [_format_cell(row, column, extrema) for column in columns]
        lines.append("\n  " + "\n  & ".join(cells) + r" \\")
    lines.extend([r"\bottomrule", r"\end{longtblr}"])
    return lines


def _generic_colspec(columns: tuple[ColumnSpec, ...], weights: tuple[float, ...]) -> str:
    specs = []
    for column, weight in zip(columns, weights):
        align = "l" if column.fmt == "text" or column.raw_latex else "c"
        specs.append(f"    X[{weight:.2f},{align},m]")
    return "\n".join(specs)


def _generic_header_row(columns: tuple[ColumnSpec, ...]) -> str:
    headers = [rf"\SetCell{{m}} \tiny\textbf{{{column.header}}}" for column in columns]
    return "\n  " + "\n  & ".join(headers) + r" \\"


def _column_extrema(frame: pd.DataFrame, columns: tuple[ColumnSpec, ...]) -> dict[str, tuple[float, float]]:
    extrema: dict[str, tuple[float, float]] = {}
    for column in columns:
        if column.higher_is_better is None:
            continue
        values = pd.to_numeric(frame.get(column.key, pd.Series(dtype=float)), errors="coerce").dropna()
        if not values.empty:
            extrema[column.key] = (float(values.min()), float(values.max()))
    return extrema


def _speed_colspec() -> str:
    alignments = ["l", "l", "c", "c"] + ["c"] * len(SPEED_METRICS)
    return "\n".join(f"    X[{weight:.2f},{align},m]" for weight, align in zip(SPEED_TABLE_WEIGHTS, alignments))


def _speed_header_row() -> str:
    headers = [
        r"\SetCell{m} \tiny\textbf{$v_0$}",
        r"\SetCell{m} \tiny\textbf{Cluster}",
        r"\SetCell{m} \tiny\textbf{$h$}",
        r"\SetCell{m} \tiny\textbf{$n$}",
    ]
    headers.extend(rf"\SetCell{{m}} \tiny\textbf{{{column.header}}}" for column in SPEED_METRICS)
    return "\n  " + "\n  & ".join(headers) + r" \\"


def _speed_metric_extrema(frame: pd.DataFrame) -> dict[str, tuple[float, float]]:
    extrema: dict[str, tuple[float, float]] = {}
    for metric in SPEED_METRICS:
        values = pd.to_numeric(frame.get(metric.source, pd.Series(dtype=float)), errors="coerce").dropna()
        if not values.empty:
            extrema[metric.source] = (float(values.min()), float(values.max()))
    return extrema


def _format_speed_metric(row: pd.Series, metric: SpeedMetric, extrema: dict[str, tuple[float, float]]) -> str:
    value = row.get(metric.source, math.nan)
    number = _finite_float(value)
    if number is None:
        return "--"
    text = _format_count_rate(row, rate=number, count_key=metric.count_source, denom_key="launch_count") if metric.fmt == "pct" and metric.count_source else _format_number(number, metric.fmt)
    limits = extrema.get(metric.source)
    if limits is None or math.isclose(limits[0], limits[1], rel_tol=0.0, abs_tol=1e-12):
        return text
    best = limits[1] if metric.higher_is_better else limits[0]
    worst = limits[0] if metric.higher_is_better else limits[1]
    if _format_number(best, metric.fmt) == _format_number(worst, metric.fmt):
        return text
    return _colour_if_extreme(number, text, best, worst)


def _format_cell(row: pd.Series, column: ColumnSpec, extrema: dict[str, tuple[float, float]]) -> str:
    value = row.get(column.key, math.nan)
    if column.fmt == "text":
        if _is_missing(value):
            return "--"
        text = str(value) if column.raw_latex else latex_escape(str(value))
        return text
    number = _finite_float(value)
    if number is None:
        return "--"
    if column.fmt == "pct" and column.count_key and column.denom_key:
        text = _format_count_rate(row, rate=number, count_key=column.count_key, denom_key=column.denom_key)
    else:
        text = _format_number(number, column.fmt)
    limits = extrema.get(column.key)
    if limits is None or column.higher_is_better is None or math.isclose(limits[0], limits[1], rel_tol=0.0, abs_tol=1e-12):
        return text
    best = limits[1] if column.higher_is_better else limits[0]
    worst = limits[0] if column.higher_is_better else limits[1]
    if _format_number(best, column.fmt) == _format_number(worst, column.fmt):
        return text
    return _colour_if_extreme(number, text, best, worst)


def _format_count_rate(row: pd.Series, *, rate: float, count_key: str | None, denom_key: str | None) -> str:
    count = _finite_float(row.get(count_key, math.nan)) if count_key else None
    total = _finite_float(row.get(denom_key, math.nan)) if denom_key else None
    if count is None or total is None:
        return _format_number(rate, "pct")
    return f"{int(round(count))}/{int(round(total))} ({100.0 * rate:.1f})"


def _format_number(number: float, fmt: str) -> str:
    if fmt == "int":
        return str(int(round(number)))
    if fmt == "pct":
        return f"{100.0 * number:.1f}"
    if fmt == "float1":
        return f"{number:.1f}"
    if fmt == "float2":
        return f"{number:.2f}"
    if fmt == "float3":
        return f"{number:.3f}"
    if fmt == "score":
        return f"{number:.1f}"
    if fmt in {"energy", "time"}:
        return f"{number:.2f}"
    return f"{number:.2f}"


def _colour_if_extreme(number: float, text: str, best: float, worst: float) -> str:
    if math.isclose(number, best, rel_tol=0.0, abs_tol=1e-12):
        return rf"\textcolor{{ICLBlue}}{{{text}}}"
    if math.isclose(number, worst, rel_tol=0.0, abs_tol=1e-12):
        return rf"\textcolor{{ICLRed}}{{{text}}}"
    return text


def _format_count(value: object) -> str:
    number = _finite_float(value)
    return "--" if number is None else str(int(round(number)))


def _safe_div(numer: object, denom: object) -> pd.Series | float:
    numer_series = pd.to_numeric(numer, errors="coerce")
    denom_series = pd.to_numeric(denom, errors="coerce")
    result = numer_series / denom_series
    if isinstance(result, pd.Series):
        return result.replace([float("inf"), float("-inf")], pd.NA)
    return result if math.isfinite(float(result)) else math.nan


def _finite_float(value: object) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def _is_missing(value: object) -> bool:
    if value is None:
        return True
    try:
        return bool(pd.isna(value))
    except (TypeError, ValueError):
        return False


def _sum_bool(values: Iterable[object]) -> int:
    return int(pd.Series(values).astype(bool).sum())


def _order_by_case(frame: pd.DataFrame) -> pd.DataFrame:
    ordered = frame.copy()
    ordered["case_order"] = ordered["library_size_case_id"].map({key: i for i, key in enumerate(LIBRARY_ORDER)})
    return ordered.sort_values("case_order")


def _read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(path)
    return pd.read_csv(path)


def _read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _human_label(value: object) -> str:
    text = str(value)
    replacements = {
        "boundary_near": "Boundary-near",
        "inflight_stable": "In-flight stable",
        "launch_gate": "Launch gate",
        "recovery_gate": "Recovery gate",
        "post_launch_degraded": "Post-launch degraded",
        "controlled_xy_boundary_terminal": "Controlled side/front boundary terminal",
        "model_boundary_only": "Model boundary only",
        "success": "Success",
        "accepted": "Accepted",
        "weak": "Weak",
        "floor_margin_stop": "Floor margin stop",
        "ceiling_margin_stop": "Ceiling margin stop",
        "no_viable_continuation_primitive": "No viable continuation primitive",
        "wall_boundary_exit_retained": "Wall boundary exit retained",
        "wall_boundary_exit_uncontrolled": "Wall boundary exit uncontrolled",
        "claim_bearing_hard_failure": "Claim-bearing hard failure",
        "claim_bearing_rollout": "Claim-bearing rollout",
        "expected_low_energy_dry_air_sink_not_governor_failure": "Expected low-energy dry-air sink",
        "physically_impossible_initial_state": "Physically impossible initial state",
    }
    if text in replacements:
        return replacements[text]
    return text.replace("_", " ").replace("-", " ").title()


def _r7_failure_interpretation(value: object) -> str:
    text = str(value)
    mapping = {
        "success": "Replay remains within the usable transition envelope and is available for later compression.",
        "controlled_xy_boundary_terminal": "The primitive reaches a controlled lateral or terminal boundary; retained as terminal evidence rather than a controller instability.",
        "model_boundary_only": "The replay leaves the local model envelope without a claim-bearing crash; used to mark limited continuation validity.",
        "accepted": "Accepted survival outcome used as strong evidence for compression.",
        "weak": "Weak but physically interpretable outcome retained only where route usability remains defensible.",
    }
    return mapping.get(text, "Physical survival-screening outcome retained for coverage and failure analysis.")


def _termination_interpretation(value: object) -> str:
    mapping = {
        "floor_margin_stop": "Usually indicates insufficient launch energy or sink before a viable continuation, especially in low-speed bins.",
        "ceiling_margin_stop": "Upper flight-envelope boundary reached; treated as a safety termination rather than a successful target arrival.",
        "no_viable_continuation_primitive": "The current library has no safe candidate for the local state, identifying a library-coverage limit.",
        "wall_boundary_exit_retained": "The trajectory exits through a wall boundary while retaining safe termination evidence.",
        "wall_boundary_exit_uncontrolled": "Wall exit without retained terminal control; counted separately from front-wall target success.",
    }
    return mapping.get(value, "Terminal event retained for physical failure interpretation.")


def _episode_interpretation(value: object) -> str:
    mapping = {
        "claim_bearing_hard_failure": "A failure mode that remains relevant to the controller/library claim.",
        "claim_bearing_rollout": "A normal claim-bearing rollout used in mission, memory, and safety statistics.",
        "expected_low_energy_dry_air_sink_not_governor_failure": "Low-energy sink case where reaching the target may be physically infeasible.",
        "physically_impossible_initial_state": "Initial condition outside a physically meaningful launch envelope.",
    }
    return mapping.get(value, "Episode-level interpretation retained for post-run analysis.")


def _timing_scope_label(value: object) -> str:
    text = str(value)
    mapping = {
        "overall": "Overall diagnostic",
        "real_flight_required:heavy_balanced": "Heavy/balanced real-flight tiers",
        "real_flight_optional_extended:light_super_light": "Light/super-light diagnostics",
        "offline_reference:no_cluster_no_merge": "No-cluster offline reference",
    }
    if text in mapping:
        return mapping[text]
    return _human_label(text.split(",", 1)[0])


def _compact_tau_string(value: object) -> str:
    text = str(value)
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        return text
    if not isinstance(parsed, list) or not parsed:
        return text
    rounded = [round(float(item), 3) for item in parsed]
    if len(set(rounded)) == 1:
        return f"{rounded[0]:.3f} s on all aggregate surfaces"
    return ", ".join(f"{item:.3f}" for item in rounded) + " s"


def latex_escape(text: str) -> str:
    return (
        str(text)
        .replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
    )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate appendix evidence-chain tables in thesis tblr style.")
    parser.add_argument("--r5-root", type=Path, default=DEFAULT_R5_ROOT)
    parser.add_argument("--r7-root", type=Path, default=DEFAULT_R7_ROOT)
    parser.add_argument("--r8-library-root", type=Path, default=DEFAULT_R8_LIBRARY_ROOT)
    parser.add_argument("--r8-outcome-root", type=Path, default=DEFAULT_R8_OUTCOME_ROOT)
    parser.add_argument("--r10-root", type=Path, default=DEFAULT_R10_ROOT)
    parser.add_argument("--r11-root", type=Path, default=DEFAULT_R11_ROOT)
    parser.add_argument(
        "--extra-r11-root",
        type=Path,
        action="append",
        help="Additional R11 validation root to include in the reproducibility summary.",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


if __name__ == "__main__":
    main()
