from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from pathlib import Path

import pandas as pd


DEFAULT_INPUT = Path("03_Control/05_Results/R11_validation/D01/metrics/speed_bin_policy_ladder_summary.csv")
DEFAULT_OUTPUT = Path("03_Control/A_figures/R11_D01_appendix_tables/r11_d01_speed_cluster_policy_appendix_tables.tex")

SPEED_ORDER = (
    "v0_lt_4_0_m_s",
    "v0_4_0_to_5_0_m_s",
    "v0_5_0_to_6_0_m_s",
    "v0_6_0_to_7_0_m_s",
    "v0_ge_7_0_m_s",
)
SPEED_LABELS = {
    "v0_lt_4_0_m_s": r"$<4.0$",
    "v0_4_0_to_5_0_m_s": r"$4.0$--$5.0$",
    "v0_5_0_to_6_0_m_s": r"$5.0$--$6.0$",
    "v0_6_0_to_7_0_m_s": r"$6.0$--$7.0$",
    "v0_ge_7_0_m_s": r"$\geq 7.0$",
}

LIBRARY_ORDER = (
    "heavy_cluster",
    "balanced_cluster",
    "light_cluster",
    "super_light_cluster",
    "no_cluster_no_merge",
)
LIBRARY_LABELS = {
    "heavy_cluster": "Heavy",
    "balanced_cluster": "Balanced",
    "light_cluster": "Light",
    "super_light_cluster": "Super-light",
    "no_cluster_no_merge": "No-cluster",
}

POLICY_ORDER = (
    "no_memory_baseline",
    "spatial_flow_belief_memory_h3",
    "spatial_flow_belief_memory_h10",
    "spatial_flow_belief_memory_h30",
)
POLICY_LABELS = {
    "no_memory_baseline": "$h=0$",
    "spatial_flow_belief_memory_h3": "$h=3$",
    "spatial_flow_belief_memory_h10": "$h=10$",
    "spatial_flow_belief_memory_h30": "$h=30$",
}

LADDER_ORDER = (
    "r11_l0_dry_air_fixed",
    "r11_l1_single_fan_fixed_nominal",
    "r11_l2_four_fan_fixed_nominal",
    "r11_l3_fan_parameter_uncertainty",
    "r11_l4_local_fan_position_uncertainty",
    "r11_l5_active_fan_count_uncertainty",
    "r11_l6_environment_only_full_uncertainty",
    "r11_l7_full_domain_randomisation_arena_wide",
)
LADDER_LABELS = {
    "r11_l0_dry_air_fixed": "L0 dry air fixed",
    "r11_l1_single_fan_fixed_nominal": "L1 single-fan fixed nominal",
    "r11_l2_four_fan_fixed_nominal": "L2 four-fan fixed nominal",
    "r11_l3_fan_parameter_uncertainty": "L3 fan-parameter uncertainty",
    "r11_l4_local_fan_position_uncertainty": "L4 local fan-position uncertainty",
    "r11_l5_active_fan_count_uncertainty": "L5 active fan-count uncertainty",
    "r11_l6_environment_only_full_uncertainty": "L6 environment-only full uncertainty",
    "r11_l7_full_domain_randomisation_arena_wide": "L7 full-domain arena-wide randomisation",
}


@dataclass(frozen=True)
class MetricColumn:
    source: str
    header: str
    formatter: str
    higher_is_better: bool


METRIC_COLUMNS = (
    MetricColumn("mission_success_rate", r"Target", "rate", True),
    MetricColumn("safe_success_rate", r"Safe", "rate", True),
    MetricColumn("front_wall_terminal_success_rate", r"Front", "rate", True),
    MetricColumn("wrong_wall_exit_rate", r"Side", "rate", False),
    MetricColumn("expected_low_energy_dry_air_sink_rate", r"Sink", "rate", False),
    MetricColumn("no_viable_primitive_rate", r"NoPr", "rate", False),
    MetricColumn("hard_failure_rate", r"Hard", "rate", False),
    MetricColumn("mean_launch_score", r"$\bar{J}$", "score", True),
    MetricColumn("median_launch_score", r"$\tilde{J}$", "score", True),
    MetricColumn("mean_terminal_specific_energy_m", r"$E_T$", "energy", True),
    MetricColumn("mean_terminal_specific_energy_reserve_m", r"$E_R$", "energy", True),
    MetricColumn("mean_positive_specific_energy_gain_m", r"$E_+$", "energy", True),
    MetricColumn("mean_updraft_specific_energy_gain_proxy_m", r"$E_u$", "energy", True),
    MetricColumn("mean_lift_dwell_time_s", r"$t_L$", "time", True),
)


COLSPEC_WEIGHTS = (
    1.30,
    1.45,
    0.50,
    0.45,
    0.85,
    0.80,
    0.80,
    0.75,
    0.80,
    0.75,
    0.75,
    1.05,
    1.05,
    1.00,
    1.00,
    1.00,
    1.00,
    0.90,
)


def main() -> None:
    args = _parse_args()
    frame = pd.read_csv(args.input)
    tex = build_appendix_tables(frame, source_path=args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(tex, encoding="ascii")
    print(args.output)


def build_appendix_tables(frame: pd.DataFrame, *, source_path: Path) -> str:
    ordered = frame.copy()
    ordered["environment_block_id"] = pd.Categorical(ordered["environment_block_id"], LADDER_ORDER, ordered=True)
    ordered["launch_speed_bin_id"] = pd.Categorical(ordered["launch_speed_bin_id"], SPEED_ORDER, ordered=True)
    ordered["library_size_case_id"] = pd.Categorical(ordered["library_size_case_id"], LIBRARY_ORDER, ordered=True)
    ordered["policy_id"] = pd.Categorical(ordered["policy_id"], POLICY_ORDER, ordered=True)
    ordered = ordered.sort_values(["environment_block_id", "launch_speed_bin_id", "library_size_case_id", "policy_id"])

    lines = [
        r"% Auto-generated by 03_Control/01_Plotting/run_r11_appendix_speed_tables.py.",
        rf"% Source: {latex_escape(str(source_path).replace('\\', '/'))}",
        r"% Each table uses width=16.2cm. Column X weights sum to 16.2.",
        r"\subsection{Held-Out Repeated-Launch Validation Tables}",
        "",
        r"\noindent\footnotesize",
        r"These appendix tables report the held-out repeated-launch validation used to test whether a fixed primitive library and an outer-loop governor can reach the front-wall target region while exploiting uncertain indoor updrafts.",
        r"Each row is one experimental condition: initial launch-speed bin $v_0$, primitive-library compression tier, and repeated-launch history length $h$.",
        r"The same paired launch starts are reused across environment ladders, library tiers, and memory policies, so rows can be compared directly within the same speed bin.",
        r"The no-memory baseline is $h=0$; $h=3$, $h=10$, and $h=30$ use the previous 3, 10, or 30 launches to update the online spatial flow-belief map.",
        r"Rates are percentages. $n$ is the number of held-out launches in the row. Target is successful arrival at the front-wall target region; Safe is retained safe termination without hard boundary failure; Front is any front-wall terminal exit; Side is wrong-wall exit; Sink is a physically low-energy floor stop; NoPr is no viable continuation primitive; Hard is a claim-bearing hard failure.",
        r"$\bar{J}$ and $\tilde{J}$ are the mean and median mission scores. $E_T$ is terminal specific energy, $E_R$ is terminal energy reserve, $E_+$ is positive specific-energy gain, $E_u$ is updraft energy-gain proxy, and $t_L$ is lift dwell time.",
        r"Blue marks the best value and red marks the worst value within each environment-ladder table for each metric column; lower is better for Side, Sink, NoPr, and Hard, while higher is better for the remaining metrics.",
        "",
    ]
    for ladder_id in LADDER_ORDER:
        ladder_frame = ordered[ordered["environment_block_id"].astype(str) == ladder_id]
        if ladder_frame.empty:
            continue
        lines.extend(_ladder_table(ladder_id, ladder_frame))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _ladder_table(ladder_id: str, frame: pd.DataFrame) -> list[str]:
    table_id = ladder_id.replace("r11_", "").replace("_", "-")
    caption = (
        f"Held-out repeated-launch validation under {LADDER_LABELS[ladder_id]}. "
        "Rows condition performance on launch speed, primitive-library compression, and the number of previous launches used by the memory-assisted governor."
    )
    label = f"tab:r11-d01-{table_id}-speed-cluster-policy"
    metric_extrema = _metric_extrema(frame)
    lines = [
        r"\begin{longtblr}[",
        rf"  caption = {{{caption}}},",
        rf"  label = {{{label}}},",
        r"]{",
        r"  rows={font=\tiny},",
        r"  width=16.2cm,",
        r"  rowhead=1,",
        r"  rowsep=1pt,",
        r"  colsep=1pt,",
        r"  colspec = {",
        _colspec(),
        r"  },",
        r"}",
        r"\toprule",
        _header_row(),
        r"\midrule",
    ]
    row_counter = 0
    for speed_id in SPEED_ORDER:
        speed_frame = frame[frame["launch_speed_bin_id"].astype(str) == speed_id]
        if speed_frame.empty:
            continue
        if row_counter:
            lines.append(r"\midrule")
        speed_started = False
        for library_id in LIBRARY_ORDER:
            library_frame = speed_frame[speed_frame["library_size_case_id"].astype(str) == library_id]
            if library_frame.empty:
                continue
            library_started = False
            for policy_id in POLICY_ORDER:
                row = library_frame[library_frame["policy_id"].astype(str) == policy_id]
                if row.empty:
                    continue
                lines.append(_table_row(row.iloc[0], speed_id, library_id, policy_id, metric_extrema, speed_started, library_started))
                speed_started = True
                library_started = True
                row_counter += 1
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtblr}",
        ]
    )
    return lines


def _colspec() -> str:
    alignments = ["l", "l", "c", "c"] + ["c"] * len(METRIC_COLUMNS)
    specs = [f"    X[{weight:.2f},{align},m]" for weight, align in zip(COLSPEC_WEIGHTS, alignments)]
    return "\n".join(specs)


def _header_row() -> str:
    headers = [
        r"\SetCell{m} \tiny\textbf{$v_0$}",
        r"\SetCell{m} \tiny\textbf{Cluster}",
        r"\SetCell{m} \tiny\textbf{$h$}",
        r"\SetCell{m} \tiny\textbf{$n$}",
    ]
    headers.extend(rf"\SetCell{{m}} \tiny\textbf{{{column.header}}}" for column in METRIC_COLUMNS)
    return "\n  " + "\n  & ".join(headers) + r" \\"


def _table_row(
    row: pd.Series,
    speed_id: str,
    library_id: str,
    policy_id: str,
    metric_extrema: dict[str, tuple[float, float]],
    speed_started: bool,
    library_started: bool,
) -> str:
    cells = []
    if not speed_started:
        cells.append(rf"\SetCell[r=20]{{l,m}} {SPEED_LABELS[speed_id]}")
    else:
        cells.append("")
    if not library_started:
        cells.append(rf"\SetCell[r=4]{{l,m}} {LIBRARY_LABELS[library_id]}")
    else:
        cells.append("")
    cells.append(POLICY_LABELS[policy_id])
    cells.append(_format_count(row.get("launch_count", "")))
    for metric in METRIC_COLUMNS:
        cells.append(_format_metric_value(row.get(metric.source, math.nan), metric, metric_extrema))
    return "\n  " + "\n  & ".join(cells) + r" \\"


def _metric_extrema(frame: pd.DataFrame) -> dict[str, tuple[float, float]]:
    extrema: dict[str, tuple[float, float]] = {}
    for metric in METRIC_COLUMNS:
        values = pd.to_numeric(frame.get(metric.source, pd.Series(dtype=float)), errors="coerce").dropna()
        if values.empty:
            continue
        extrema[metric.source] = (float(values.min()), float(values.max()))
    return extrema


def _format_metric_value(value: object, metric: MetricColumn, metric_extrema: dict[str, tuple[float, float]]) -> str:
    number = _finite_float(value)
    if number is None:
        return "--"
    if metric.formatter == "rate":
        text = f"{100.0 * number:.1f}"
    elif metric.formatter == "score":
        text = f"{number:.1f}"
    elif metric.formatter in {"energy", "time"}:
        text = f"{number:.2f}"
    else:
        text = f"{number:.2f}"
    extrema = metric_extrema.get(metric.source)
    if extrema is None or math.isclose(extrema[0], extrema[1], rel_tol=0.0, abs_tol=1e-12):
        return text
    best = extrema[1] if metric.higher_is_better else extrema[0]
    worst = extrema[0] if metric.higher_is_better else extrema[1]
    if math.isclose(number, best, rel_tol=0.0, abs_tol=1e-12):
        return rf"\textcolor{{ICLBlue}}{{{text}}}"
    if math.isclose(number, worst, rel_tol=0.0, abs_tol=1e-12):
        return rf"\textcolor{{ICLRed}}{{{text}}}"
    return text


def _format_count(value: object) -> str:
    number = _finite_float(value)
    if number is None:
        return "--"
    return str(int(round(number)))


def _finite_float(value: object) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def latex_escape(text: str) -> str:
    return (
        str(text)
        .replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
    )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate appendix R11 speed/cluster/history tables in thesis tblr style.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


if __name__ == "__main__":
    main()
