% DEBUG_TRANSMITTER_MINIMAL Minimal reproducible transmitter latency run.
% Run this script to isolate one surface with import-only capture analysis.

config = struct();
config.commandMode = "single";
config.singleSurfaceName = "Aileron_R";
config.commandProfile = struct( ...
    "type", "latency_isolated_step", ...
    "preCommandNeutralSeconds", 1.0, ...
    "durationSeconds", 8.0, ...
    "postCommandNeutralSeconds", 1.0, ...
    "randomSeed", 5);
config.logicAnalyzer = struct( ...
    "enabled", true, ...
    "mode", "import_only");
config.matching = struct( ...
    "truthSubsetMode", "off");
config.debug = struct( ...
    "strictDownstreamMatching", true);

% Optional: point to manually verified capture CSV files.
% config.logicAnalyzer.referenceCapturePath = "path_to_reference.csv";
% config.logicAnalyzer.trainerPpmCapturePath = "path_to_trainer.csv";
% config.logicAnalyzer.receiverCapturePath = "path_to_receiver.csv";

runData = Transmitter_Test(config);
disp(runData.logs.alignmentSummary);
disp(runData.surfaceSummary(:, { ...
    'SurfaceName', ...
    'MatchedReceiverCount', ...
    'LatencySummarySource'}));
