function runData = See_Vicon_Test_Single()
%SEE_VICON_TEST_SINGLE Launch the baseline recorder for one tracker.
config = struct( ...
    "hostName", "localhost:801", ...
    "subjectNames", "Tracker_1", ...
    "segmentNames", struct(), ...
    "streamMode", "ServerPush", ...
    "axisMapping", "ZUp", ...
    "roomBoundsMeters", [-2.0, 2.0; -2.0, 2.0; 0.0, 2.5], ...
    "outputFolder", fullfile(fileparts(mfilename("fullpath")), "B_See_Vicon"), ...
    "workspaceUpdateDivider", 1, ...
    "runLabel", "");

runData = See_Vicon(config);
end
