function runData = See_Vicon_Test_Four()
%SEE_VICON_TEST_FOUR Launch the baseline recorder for four trackers.
config = struct( ...
    "hostName", "localhost:801", ...
    "subjectNames", ["Tracker_1"; "Tracker_2"; "Tracker_3"; "Tracker_4"], ...
    "segmentNames", struct(), ...
    "streamMode", "ServerPush", ...
    "axisMapping", "ZUp", ...
    "roomBoundsMeters", [-2.0, 2.0; -2.0, 2.0; 0.0, 2.5], ...
    "outputFolder", fullfile(fileparts(mfilename("fullpath")), "B_See_Vicon"), ...
    "workspaceUpdateDivider", 1, ...
    "runLabel", "");

runData = See_Vicon(config);
end
