function runData = Test()
%TEST Launch the baseline Vicon recorder with a single configuration struct.
config = struct( ...
    "hostName", "localhost:801", ...
    "subjectNames", strings(0, 1), ...
    "segmentNames", struct(), ...
    "streamMode", "ServerPush", ...
    "axisMapping", "ZUp", ...
    "roomBoundsMeters", [-2.0, 2.0; -2.0, 2.0; 0.0, 2.5], ...
    "outputFolder", fullfile(fileparts(mfilename("fullpath")), "B_See_Vicon"), ...
    "workspaceUpdateDivider", 1, ...
    "runLabel", "");

runData = See_Vicon(config);
end
