function rawRunFile = latestRunDataFile(mode)
%LATESTRUNDATAFILE Locate the newest raw run_data.mat for the requested mode.
%% =========================================================================
% SECTION MAP
% ==========================================================================
% 1) Search generated raw-run folders
% ==========================================================================
%% =========================================================================
% 1) Search generated raw-run folders
% ==========================================================================
arguments
    mode (1,1) string
end

root = fullfile("C_Overall_Latency", "data", "raw");
% Raw run folders are generated by Run_Control_Path and contain the authoritative run_data.mat log.
matches = dir(fullfile(root, "**", "run_data.mat"));
if isempty(matches)
    error("latestRunDataFile:NoRuns", "No run_data.mat files found under %s.", root);
end

keep = false(numel(matches), 1);
for k = 1:numel(matches)
    % Mode is encoded in the run folder name, preserving compatibility with timestamped run labels.
    keep(k) = contains(string(matches(k).folder), "_" + mode);
end
matches = matches(keep);
if isempty(matches)
    error("latestRunDataFile:NoModeRuns", "No %s run_data.mat files found under %s.", mode, root);
end

[~, idx] = max([matches.datenum]);
rawRunFile = string(fullfile(matches(idx).folder, matches(idx).name));
end
