from __future__ import annotations

import numpy as np

# Generated by build_mass_properties_estimate.py from deterministic hand estimates.
# R_CG_BUILD_M uses x aft from wing LE, y starboard, z down from fuselage rod centre.
# INERTIA_B is about the assembled CG in simulation body-axis orientation.

# =============================================================================
# SECTION MAP
# =============================================================================
# 1) Generated mass properties
# =============================================================================


# =============================================================================
# 1) Generated Mass Properties
# =============================================================================
MASS_KG = 0.1485600000000000
R_CG_BUILD_M = np.array([0.10550000000000002, 0.0, -0.008037445457381024], dtype=float)
R_CG_B = np.array([-0.10550000000000002, 0.0, -0.008037445457381024], dtype=float)
INERTIA_B = np.array([[0.0027026951327610775, 0.0, 2.3150631199284152e-05], [0.0, 0.0029875937118918686, 0.0], [2.3150631199284152e-05, 0.0, 0.005606240152469395]], dtype=float)
