from __future__ import annotations

import numpy as np

# Generated by build_mass_properties_estimate.py from deterministic hand estimates.
# R_CG_BUILD_M uses x aft from wing LE, y starboard, z down from fuselage rod centre.
# INERTIA_B is about the assembled CG in simulation body-axis orientation.

# =============================================================================
# SECTION MAP
# =============================================================================
# 1) Generated mass properties
# =============================================================================


# =============================================================================
# 1) Generated Mass Properties
# =============================================================================
MASS_KG = 0.1335600000000000
R_CG_BUILD_M = np.array([0.126, 0.0, -0.008940123518632263], dtype=float)
R_CG_B = np.array([-0.126, 0.0, -0.008940123518632263], dtype=float)
INERTIA_B = np.array([[0.002701617296433628, 0.0, 4.762851059082893e-05], [0.0, 0.002458805568208538, 0.0], [4.762851059082893e-05, 0.0, 0.005078529845113513]], dtype=float)
