from __future__ import annotations

import numpy as np


# =============================================================================
# SECTION MAP
# =============================================================================
# 1) Generated mass properties
# =============================================================================

# =============================================================================
# 1) Generated Mass Properties
# =============================================================================
# Generated by build_mass_properties_estimate.py from deterministic hand estimates.
# Values use SI units and body axes about the assembled vehicle CG.
MASS_KG = 0.1175000000000000
R_CG_B = np.array([-0.0135740622257916, 0.0, -0.005440281315318704], dtype=float)
INERTIA_B = np.array([[0.00151933300957369, 0.0, 0.00017097042142330622], [0.0, 0.002861244928207894, 0.0], [0.00017097042142330622, 0.0, 0.004303334576872342]], dtype=float)
