function runData = See_Vicon_Test_Four()
%SEE_VICON_TEST_FOUR Launch the baseline recorder for four trackers.
config = struct( ...
    "hostName", "192.168.0.100:801", ...
    "subjectNames", ["Nausicaa_Test_00"; "Nausicaa_Test_01"; "Nausicaa_Test_02"; "Nausicaa_Test_03"], ...
    "segmentNames", struct(), ...
    "streamMode", "ServerPush", ...
    "axisMapping", "ZUp", ...
    "roomBoundsMeters", [-4.2, 4.2; -4.2, 4.2; 0.0, 3.5], ...
    "outputFolder", fullfile(fileparts(mfilename("fullpath")), "B_See_Vicon"), ...
    "workspaceUpdateDivider", 1, ...
    "runLabel", "");

runData = See_Vicon(config);
end
