function runData = See_Vicon_Test_Single()
%SEE_VICON_TEST_SINGLE Launch the baseline recorder for one tracker.
config = struct( ...
    "hostName", "192.168.0.100:801", ...
    "subjectNames", "Nausicaa_Test_00", ...
    "segmentNames", struct(), ...
    "streamMode", "ServerPush", ...
    "axisMapping", "ZUp", ...
    "roomBoundsMeters", [-4.2, 4.2; -4.2, 4.2; 0.0, 3.5], ...
    "outputFolder", fullfile(fileparts(mfilename("fullpath")), "B_See_Vicon"), ...
    "workspaceUpdateDivider", 1, ...
    "runLabel", "");

runData = See_Vicon(config);
end
